# Generated by Django 3.2.19 on 2023-07-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230710_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
