# Generated by Django 5.1.7 on 2025-03-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230710_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_Email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
