# Generated by Django 5.1.7 on 2025-03-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_is_email_verified'),
        ('products', '0005_remove_product_color_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcolorvariant'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productsizevariant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profile_Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
