# Generated by Django 5.1.7 on 2025-03-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_cartitems_color_variant_and_more'),
        ('products', '0005_remove_product_color_variant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColorVariant',
        ),
        migrations.DeleteModel(
            name='SizeVariant',
        ),
    ]
