# Generated by Django 5.1.7 on 2025-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_colorvariant_delete_sizevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
