# Generated by Django 5.1.7 on 2025-03-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcolorvariant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolorvariant',
            name='image',
        ),
        migrations.AddField(
            model_name='productcolorvariant',
            name='product_images',
            field=models.ManyToManyField(related_name='color_variants', to='products.productimage'),
        ),
    ]
