# Generated by Django 5.1.7 on 2025-03-28 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productcolorvariant_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolorvariant',
            name='product_images',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='products.productcolorvariant'),
        ),
    ]
