# Generated by Django 5.1.7 on 2025-03-29 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productcolorvariant_product_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Availability',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='productcolorvariant',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
